# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:

        # name our filter set "my_crop_filter"
        squared_thumbnail_medium:
            filters:

                # use and setup the "crop" filter
                thumbnail:

                    # set the size of the cropping area
                    size: [ 300, 300 ]

                    # set the starting coordinates of the crop
                    mode: outbound
                    allow_upscale: true
        squared_thumbnail_small:
            filters:
                thumbnail:

                    # set the size of the cropping area
                    size: [ 200, 200 ]

                    # set the starting coordinates of the crop
                    mode: outbound
                    allow_upscale: true