# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # name our filter set "my_fixed_filter"
        my_fixed_filter:
            filters:
                # use and setup the "fixed" filter
                thumbnail: {size:[50,50], mode: outbound, allow_upscale: true }

